# Suppose Sabin Nepal joined your team on the first day of 2020 as special contractor to work for a span of 3 years, ie, till the end of the year 2023. He needs his accounts on remote hosts till his work span.


# Write a playbook add_user.yml to create his user account with username neymarsabin that would be expiring after 3 years. The expires option on the users module is in the epoch. So Sunday, December 31, 2023 11:59:59 PM GMT== 1704067199 as epoch time

# Remember: your playbook must be placed inside /home/thor/playbooks and use inventory file there.

---
- hosts: all
  gather_facts: no
  tasks:
    - user:
        name: 'neymarsabin'
        expires: 1704067199