---
- hosts: all
  tasks:
    - block:
        - yum: 
            name: httpd
            state: installed
        - service:
            name: httpd
            state: started 
      when: ansible_facts['distribution'] == 'CentOS'
