# Create a playbook download.yml under ~/playbooks to download and extract https://github.com/kodekloudhub/Hello-World/archive/master.zip zip archive under /root directory on web1 node.

- name: Download and extract from URL
  hosts: web1
  tasks:
   - unarchive:
       src: https://github.com/kodekloudhub/Hello-World/archive/master.zip
       dest: /root
       remote_src: yes