#playbook ~/playbooks/find.yml that recursively find files in /opt/data directory older than 2 minutes and equal or greater than 1 megabyte in size and also copy that files under /opt directory.

---
- hosts: web1
  tasks:
    - name: Find files
      find:
        paths: /opt/data
        size: 1m
        age: 2m
        recurse: yes
      register: file

    - name: Copy files
      command: "cp {{ item.path }} /opt"
      with_items: "{{ file.files }}"